# Generated by Django 5.0.2 on 2024-02-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=200)),
                ("data_time", models.DateTimeField()),
                ("location", models.CharField(max_length=200)),
                ("number_event", models.BigIntegerField()),
                ("source_link", models.URLField()),
                ("manager", models.CharField(max_length=200)),
                ("announcement_number", models.BigIntegerField()),
                ("sector", models.CharField(max_length=200)),
                ("ticket_quantity", models.IntegerField()),
                ("link_viagogo", models.URLField()),
                ("features", models.CharField(blank=True, max_length=200, null=True)),
                ("state", models.CharField(max_length=100)),
                (
                    "source_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("net_price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("profit_percentage", models.IntegerField(blank=True, null=True)),
                ("bot", models.IntegerField()),
            ],
        ),
    ]
