# Generated by Django 5.0.2 on 2024-03-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="coeff_max_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="bot",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
