# Generated by Django 5.0.2 on 2024-03-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_tracking", "0002_event_coeff_max_price_alter_event_bot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="ticket_quantity",
            field=models.FloatField(),
        ),
    ]
