# Generated by Django 5.0.2 on 2024-03-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_tracking", "0003_alter_event_ticket_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="coeff_max_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="ticket_quantity",
            field=models.IntegerField(),
        ),
    ]
