# Generated by Django 5.0.2 on 2024-03-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_tracking", "0004_alter_event_coeff_max_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="coeff_max_price",
            new_name="coefficient",
        ),
        migrations.AddField(
            model_name="event",
            name="commission",
            field=models.FloatField(default=1.015),
        ),
        migrations.AlterField(
            model_name="event",
            name="link_viagogo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="manager",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="source_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
