# Generated by Django 5.0.2 on 2024-03-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_tracking", "0005_rename_coeff_max_price_event_coefficient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="profit_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=4, null=True
            ),
        ),
    ]
