services:
  web:
    build: .
    volumes:
      - ./service:/service
    restart: on-failure

  worker-1:
    build: .
    volumes:
      - ./service:/service
    command: python manage.py runserver
    ports:
      - '80:80'
    restart:  on-failure

  worker-2:
    build: .
    volumes:
      - ./service:/service
    command: python manage.py via_parser
    restart: on-failure